### ISSUE TITLE
Link to website in description

### ISSUE THREAD

**Issue by Panquesito7** [mishraabhinn/Portfolio#1]

**Comment by mishraabhinn** [comment]
I have provided it directly in my bio. 
But will provide in description too. 
Thank you.

**Comment by Panquesito7** [comment]
It's in `README.md`, but I meant in the repository description (in the `About` gear).
For example, see https://github.com/minetest/minetest at right.

**Comment by mishraabhinn** [comment]
> It's in `README.md`, but I meant in the repository description (in the `About` gear).
> For example, see https://github.com/minetest/minetest at right.

I thought in the repo description. 
Ty.
